function run_parse_polan_synced(filepath, fscale, hm, fm)
    % run_parse_polan_synced
    % Batch processes all .pol files in the given directory tree,
    % extracting data to .mat, saving plots, and generating log files.
    
    % Validate input limits
    if length(hm) ~= 2 || length(fm) ~= 2
        error('hm and fm must be 2-element arrays [min, max].');
    end
    hmin = hm(1); hmax = hm(2);
    fmin = fm(1); fmax = fm(2);

    % Initialize Log Files in the root of filepath
    log_mat_png = fullfile(filepath, 'sync_mat_png.log');
    log_err     = fullfile(filepath, 'sync_err.log');
    
    fid_log = fopen(log_mat_png, 'wt');
    if fid_log == -1
        error('Cannot create log file at %s', log_mat_png);
    end
    
    fid_err = fopen(log_err, 'wt');
    if fid_err == -1
        fclose(fid_log);
        error('Cannot create error log file at %s', log_err);
    end
    
    fprintf(fid_log, '=== BATCH PROCESSING LOG ===\n');
    fprintf(fid_log, 'Started at: %s\n\n', datestr(now));
    
    fprintf(fid_err, '=== FILES WITH PARSING ERRORS ===\n');
    fprintf(fid_err, 'Started at: %s\n\n', datestr(now));

    fprintf('Scanning directory %s for .pol files...\n', filepath);
    
    % Find all .pol files recursively
    pol_files = dir(fullfile(filepath, '**', '*.pol'));
    total_files = length(pol_files);
    
    if total_files == 0
        fprintf('No .pol files found in the specified directory.\n');
        fclose(fid_log);
        fclose(fid_err);
        return;
    end
    
    fprintf('Found %d .pol files. Starting batch processing...\n', total_files);
    
    for i = 1:total_files
        folder = pol_files(i).folder;
        filename = pol_files(i).name;
        
        fprintf('[%d/%d] Processing: %s\n', i, total_files, filename);
        
        try
            % Parse file and generate .mat (saved inside parse function)
            data = parse_polan_file_synced(folder, filename);
            
            % Ensure data was returned
            if isempty(data)
                fprintf('  Warning: No valid data found in %s\n', filename);
                continue;
            end
            
            % Access the first (and usually only) record
            idx = 1;
            
            % Prepare suffixes
            [~, base_name, ~] = fileparts(filename);
            base_name_pol = [base_name, '_pol']; 
            
            has_errors = ~isempty(data(idx).Errors);
            err_suffix = '';
            if has_errors
                err_suffix = '_err';
            end

            scale_suffix = '';
            if strcmpi(fscale, 'lin')
                scale_suffix = '_lin';
            end
            
            % Expected MAT filename generated by parse_polan_file_synced
            mat_filename = fullfile(folder, [base_name_pol, '.mat']);
            
            % Log to error file if errors were found in the .pol parsing
            if has_errors
                fprintf(fid_err, '%s\n', mat_filename);
            end
            
            % Create figure in hidden mode for fast batch processing
            fig = figure('Name', 'Ionogram Profile', 'Color', 'w', 'Visible', 'off');
            
            % Plot Virtual Heights
            if ~isempty(data(idx).InputData)
                plot(data(idx).InputData(:,1), data(idx).InputData(:,2), 'b.-', ...
                    'MarkerSize', 12, 'LineWidth', 1.5, 'DisplayName', 'Virtual heights h''');
                hold on;
            end
            
            % Plot True Heights
            if ~isempty(data(idx).RealHeights)
                plot(data(idx).RealHeights(:,1), data(idx).RealHeights(:,2), 'r.-', ...
                    'MarkerSize', 12, 'LineWidth', 1.5, 'DisplayName', 'True heights h');
            end
            
            % Check if Peak data actually contains numerical values
            has_peak = ~isempty(data(idx).Peak) && ~isempty(data(idx).Peak.foF2);

            % Highlight the F2 Peak
            if has_peak
                scatter(data(idx).Peak.foF2, data(idx).Peak.hmF2, 250, 'k', 'filled', 'p', ...
                    'DisplayName', 'F2 Peak');
            end
            
            % Generate Title
            dt = data(idx).DT;
            if has_peak
                title_str = sprintf('STATION: %s | %04d/%02d/%02d %02d:%02d (%s) foF2 = %.4f MHz; hmF2 = %.1f km', ...
                    upper(data(idx).Station), dt(1), dt(2), dt(3), dt(4), dt(5), ...
                    upper(fscale), data(idx).Peak.foF2, data(idx).Peak.hmF2);
            else
                title_str = sprintf('STATION: %s | %04d/%02d/%02d %02d:%02d (%s)', ...
                    upper(data(idx).Station), dt(1), dt(2), dt(3), dt(4), dt(5), upper(fscale));
            end

            if has_errors
                title_str = [title_str, ' [FOUND ERRORS]'];
            end
            title(title_str, 'FontSize', 12, 'FontWeight', 'bold');
            
            % Apply scales
            if strcmpi(fscale, 'lin')
                set(gca, 'XScale', 'linear');
            else
                set(gca, 'XScale', 'log');
                xticks([0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
                xticklabels({'0.5', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'});
            end

            set(gca, 'YDir', 'normal'); 
            xlabel('Frequency (MHz)', 'FontSize', 12);
            ylabel('Height (km)', 'FontSize', 12);
            legend('Location', 'best', 'FontSize', 11);
            grid on;
            
            % --- SAVE 1: Auto-scaled boundaries ---
            autoscale_filename = fullfile(folder, sprintf('%s%s_autoscale%s.png', base_name_pol, err_suffix, scale_suffix));
            saveas(fig, autoscale_filename);
            
            % --- SAVE 2: Fixed boundaries ---
            xlim([fmin fmax]);
            ylim([hmin hmax]);
            fixed_filename = fullfile(folder, sprintf('%s%s%s.png', base_name_pol, err_suffix, scale_suffix));
            saveas(fig, fixed_filename);
            
            % Log the generated files to the main log
            fprintf(fid_log, 'Processed: %s\n', filename);
            fprintf(fid_log, '  -> MAT: %s\n', mat_filename);
            fprintf(fid_log, '  -> PNG (Auto): %s\n', autoscale_filename);
            fprintf(fid_log, '  -> PNG (Fixed): %s\n\n', fixed_filename);
            
            % Close figure to prevent memory leak during batch processing
            close(fig);
            
        catch ME
            fprintf('  Critical Error processing %s: %s\n', filename, ME.message);
            fprintf(fid_log, '  [CRITICAL ERROR] Failed to process %s: %s\n\n', filename, ME.message);
            
            % Ensure figure is closed even if an error occurs
            if exist('fig', 'var') && isvalid(fig)
                close(fig);
            end
        end
    end
    
    fprintf('Batch processing complete.\n');
    
    % Close log files
    if fid_log ~= -1
        fclose(fid_log);
    end
    if fid_err ~= -1
        fclose(fid_err);
    end
end